# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  - name: tag
    value: '$(Build.BuildId)'
  - group: onboarding-app

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'dockerhub'
    repository: 'kstvakin/onboarding-app-devops'
    command: 'build'
    Dockerfile: '**/Dockerfile'
    tags: '$(tag)'
    arguments: '--build-arg DB_PASSWORD=$(DB_PASSWORD)'
- task: Docker@2
  inputs:
    containerRegistry: 'dockerhub'
    repository: 'kstvakin/onboarding-app-devops'
    command: 'push'
- task: SSH@0
  inputs:
    sshEndpoint: 'ec2-3-15-154-239.us-east-2'
    runOptions: 'inline'
    inline: 'docker kill onboarding-app'
    readyTimeout: '20000'
- task: SSH@0
  inputs:
    sshEndpoint: 'ec2-3-15-154-239.us-east-2'
    runOptions: 'inline'
    inline: 'docker run -d -p 80:3000 --name=onboarding-app kstvakin/onboarding-app-devops:$(tag)'
    readyTimeout: '20000'


