# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  tag: '$(Build.BuildId)'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'dockerhub'
    repository: 'kstvakin/onboarding-app-devops'
    command: 'build'
    Dockerfile: '**/Dockerfile'
    tags: '$(tag)'
    arguments: 'DB_USERNAME=$(DB_USERNAME) DB_PASSWORD=$(DB_PASSWORD) DB_NAME=$(DB_NAME) DB_HOSTNAME=$(DB_HOSTNAME) DB_PORT=$(DB_PORT)'
- task: SSH@0
  inputs:
    sshEndpoint: 'ec2-3-15-154-239.us-east-2'
    runOptions: 'inline'
    inline: 'docker run -d -p 80:3000 kstvakin/onboarding-app-devops:25'
    readyTimeout: '20000'


