# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: AWSShellScript@1
  inputs:
    awsCredentials: 'aws'
    regionName: 'us-east-2'
    scriptType: 'inline'
    inlineScript: 'docker run -d -p 80:3000 kstvakin/onboarding-app-devops:25'
