# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AWSCLI@1
  inputs:
    awsCredentials: 'aws'
    regionName: 'us-east-2'
    awsCommand: 'docker'
    awsSubCommand: 'run -p 80:3000 kstvakin/onboarding-app-devops:25'