version: '3.7'
services:
  onboarding-app:
    image: kstvakin/onboarding-app-devops:release
    ports:
      - "80:3000"
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    networks:
      - app-network

# Networks to be created to facilitate communication between containers
networks:
  app-network: